version: 2

sources:
  - name: RAW
    database: ANALYTICS
    schema: RAW
    tables:
      - name: MEN_FASHION
        description: "Raw data of men's fashion products from ASOS"
      - name: WOMAN_FASHION
        description: "Raw data of woman's fashion products from ASOS"
